name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
         echo "${{ secrets.password }}" | docker login -u "sravangcpdocker" --password-stdin
         docker image build -t sravangcpdocker/toolkit:new2 .
         docker push sravangcpdocker/toolkit:new2
