name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
         docker tag toolkit-test sravangcpdocker/tool-kit:1.0
         docker login -u $username -p $password'
         docker push  sravangcpdocker/tool-kit:1.0
